#!/usr/bin/env python
import rospy

if __name__ == "__main__":
	rospy.init_node("nodo_hola")
	print "Hola UTEC!"
	rospy.loginfo("Este es un mensaje normal")
	rospy.logwarn("Este es un mensaje de advertencia")
	rospy.logerr("Este es un mensaje de error")
	rospy.spin()